import { Deal, City } from "./types";

export const popularCities: City[] = [
  { code: "NYC", name: "New York", country: "USA", imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800", dealCount: 156, avgSavings: 42, slug: "new-york" },
  { code: "LAX", name: "Los Angeles", country: "USA", imageUrl: "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800", dealCount: 134, avgSavings: 38, slug: "los-angeles" },
  { code: "TYO", name: "Tokyo", country: "Japan", imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800", dealCount: 89, avgSavings: 45, slug: "tokyo" },
  { code: "PAR", name: "Paris", country: "France", imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800", dealCount: 112, avgSavings: 35, slug: "paris" },
  { code: "LDN", name: "London", country: "UK", imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800", dealCount: 98, avgSavings: 32, slug: "london" },
  { code: "BKK", name: "Bangkok", country: "Thailand", imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800", dealCount: 76, avgSavings: 52, slug: "bangkok" },
  { code: "BCN", name: "Barcelona", country: "Spain", imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800", dealCount: 67, avgSavings: 40, slug: "barcelona" },
  { code: "SYD", name: "Sydney", country: "Australia", imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800", dealCount: 54, avgSavings: 38, slug: "sydney" },
  { code: "DXB", name: "Dubai", country: "UAE", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800", dealCount: 72, avgSavings: 35, slug: "dubai" },
  { code: "ROM", name: "Rome", country: "Italy", imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800", dealCount: 88, avgSavings: 37, slug: "rome" },
  { code: "AMS", name: "Amsterdam", country: "Netherlands", imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800", dealCount: 45, avgSavings: 33, slug: "amsterdam" },
  { code: "SIN", name: "Singapore", country: "Singapore", imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800", dealCount: 61, avgSavings: 41, slug: "singapore" },
  { code: "CUN", name: "Cancun", country: "Mexico", imageUrl: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800", dealCount: 93, avgSavings: 44, slug: "cancun" },
  { code: "DPS", name: "Bali", country: "Indonesia", imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800", dealCount: 58, avgSavings: 48, slug: "bali" },
  { code: "MIA", name: "Miami", country: "USA", imageUrl: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800", dealCount: 82, avgSavings: 36, slug: "miami" },
  { code: "HNL", name: "Honolulu", country: "USA", imageUrl: "https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=800", dealCount: 47, avgSavings: 39, slug: "honolulu" },
];

export const sampleDeals: Deal[] = [
  {
    id: "1",
    type: "flight",
    title: "New York to Tokyo - Error Fare!",
    description: "Incredible mistake fare on ANA. Business class for economy prices. Book fast before it's gone! This is one of the best deals we've seen all year for premium travel to Japan.",
    originalPrice: 4500,
    currentPrice: 1289,
    currency: "USD",
    savingsPercent: 71,
    valueScore: 98,
    originCity: "New York",
    originCode: "JFK",
    destinationCity: "Tokyo",
    destinationCode: "NRT",
    departureDate: "2026-04-15",
    returnDate: "2026-04-25",
    bookByDate: "2026-03-10",
    travelWindow: "Apr - Jun 2026",
    airline: "ANA",
    includes: ["Business Class", "2 Checked Bags", "Lounge Access", "Priority Boarding"],
    restrictions: ["Non-refundable", "No changes within 7 days of departure"],
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    bookingUrl: "https://example.com/book/1",
    source: "SecretFlying",
    postedAt: "2026-03-05T08:00:00Z",
    updatedAt: "2026-03-05T08:00:00Z",
    views: 15420,
    saves: 892,
    tags: ["error-fare", "business-class", "asia", "japan"],
    isHotDeal: true,
    isExpiringSoon: true,
    isHistoricLow: true,
  },
  {
    id: "2",
    type: "package",
    title: "5 Nights in Bali - All Inclusive",
    description: "Luxury resort stay with flights included. Private pool villa, all meals, spa credit. Perfect for honeymoons or romantic getaways.",
    originalPrice: 3200,
    currentPrice: 1899,
    currency: "USD",
    savingsPercent: 41,
    valueScore: 92,
    originCity: "Los Angeles",
    originCode: "LAX",
    destinationCity: "Bali",
    destinationCode: "DPS",
    travelWindow: "Mar - May 2026",
    bookByDate: "2026-03-15",
    nights: 5,
    hotel: "COMO Uma Ubud",
    includes: ["Roundtrip Flights", "5 Nights Private Villa", "All Meals", "$100 Spa Credit", "Airport Transfer", "Daily Yoga"],
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    bookingUrl: "https://example.com/book/2",
    source: "TravelPirates",
    postedAt: "2026-03-04T14:00:00Z",
    updatedAt: "2026-03-05T06:00:00Z",
    views: 8934,
    saves: 567,
    tags: ["all-inclusive", "luxury", "honeymoon", "asia", "indonesia"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "3",
    type: "hotel",
    title: "Paris 5-Star Hotel - 50% Off",
    description: "Le Marais boutique hotel with Eiffel Tower views. Breakfast included. Walking distance to major attractions.",
    originalPrice: 450,
    currentPrice: 225,
    currency: "USD",
    savingsPercent: 50,
    valueScore: 88,
    destinationCity: "Paris",
    destinationCode: "CDG",
    travelWindow: "Mar - Apr 2026",
    bookByDate: "2026-03-20",
    nights: 1,
    hotel: "Hotel Le Pavillon de la Reine",
    includes: ["Breakfast Buffet", "Free WiFi", "Late Checkout", "Welcome Champagne"],
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    bookingUrl: "https://example.com/book/3",
    source: "Travelzoo",
    postedAt: "2026-03-03T10:00:00Z",
    updatedAt: "2026-03-05T02:00:00Z",
    views: 5621,
    saves: 334,
    tags: ["luxury", "europe", "romantic", "france"],
    isHotDeal: false,
    isExpiringSoon: false,
    isHistoricLow: true,
  },
  {
    id: "4",
    type: "flight",
    title: "Chicago to London - $399 RT",
    description: "Spring sale on British Airways. Great dates available including weekends. Direct flights from O'Hare.",
    originalPrice: 850,
    currentPrice: 399,
    currency: "USD",
    savingsPercent: 53,
    valueScore: 85,
    originCity: "Chicago",
    originCode: "ORD",
    destinationCity: "London",
    destinationCode: "LHR",
    travelWindow: "Apr - Jun 2026",
    bookByDate: "2026-03-12",
    airline: "British Airways",
    includes: ["Carry-on Bag", "Personal Item", "In-flight Entertainment"],
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    bookingUrl: "https://example.com/book/4",
    source: "The Flight Deal",
    postedAt: "2026-03-05T06:00:00Z",
    updatedAt: "2026-03-05T06:00:00Z",
    views: 7823,
    saves: 456,
    tags: ["europe", "spring-sale", "uk", "direct-flight"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "5",
    type: "package",
    title: "Cancun Beach Resort - 7 Nights",
    description: "Beachfront all-inclusive resort. Unlimited food, drinks, and activities. Adults only.",
    originalPrice: 2800,
    currentPrice: 1599,
    currency: "USD",
    savingsPercent: 43,
    valueScore: 90,
    originCity: "New York",
    originCode: "JFK",
    destinationCity: "Cancun",
    destinationCode: "CUN",
    travelWindow: "Mar - May 2026",
    bookByDate: "2026-03-18",
    nights: 7,
    hotel: "Secrets The Vine Cancun",
    includes: ["Roundtrip Flights", "7 Nights Stay", "All-Inclusive Package", "Adults Only", "Swim-up Bar"],
    imageUrl: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800",
    bookingUrl: "https://example.com/book/5",
    source: "Costco Travel",
    postedAt: "2026-03-04T16:00:00Z",
    updatedAt: "2026-03-05T04:00:00Z",
    views: 12045,
    saves: 789,
    tags: ["all-inclusive", "beach", "adults-only", "mexico", "caribbean"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "6",
    type: "flight",
    title: "San Francisco to Bangkok - $489 RT",
    description: "Amazing price on China Airlines with short layover in Taipei. Great for first-time visitors to Southeast Asia.",
    originalPrice: 1100,
    currentPrice: 489,
    currency: "USD",
    savingsPercent: 56,
    valueScore: 94,
    originCity: "San Francisco",
    originCode: "SFO",
    destinationCity: "Bangkok",
    destinationCode: "BKK",
    travelWindow: "Apr - Oct 2026",
    bookByDate: "2026-03-14",
    airline: "China Airlines",
    includes: ["Checked Bag", "Meals", "In-flight Entertainment"],
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800",
    bookingUrl: "https://example.com/book/6",
    source: "SecretFlying",
    postedAt: "2026-03-05T02:00:00Z",
    updatedAt: "2026-03-05T02:00:00Z",
    views: 6234,
    saves: 412,
    tags: ["asia", "long-haul", "value", "thailand"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: true,
  },
  {
    id: "7",
    type: "hotel",
    title: "Dubai 5-Star Resort - 40% Off",
    description: "Luxury beachfront resort with stunning views of Burj Al Arab. Includes breakfast and pool access.",
    originalPrice: 550,
    currentPrice: 329,
    currency: "USD",
    savingsPercent: 40,
    valueScore: 82,
    destinationCity: "Dubai",
    destinationCode: "DXB",
    travelWindow: "Mar - May 2026",
    bookByDate: "2026-03-25",
    nights: 1,
    hotel: "Jumeirah Beach Hotel",
    includes: ["Breakfast", "Beach Access", "Pool Access", "Gym Access"],
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    bookingUrl: "https://example.com/book/7",
    source: "Hotels.com",
    postedAt: "2026-03-04T12:00:00Z",
    updatedAt: "2026-03-05T08:00:00Z",
    views: 4521,
    saves: 287,
    tags: ["luxury", "beach", "middle-east", "uae"],
    isHotDeal: false,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "8",
    type: "flight",
    title: "Boston to Barcelona - $349 RT",
    description: "Norse Atlantic flash sale. Direct flights to Spain's most vibrant city. Limited availability.",
    originalPrice: 720,
    currentPrice: 349,
    currency: "USD",
    savingsPercent: 52,
    valueScore: 89,
    originCity: "Boston",
    originCode: "BOS",
    destinationCity: "Barcelona",
    destinationCode: "BCN",
    travelWindow: "May - Jul 2026",
    bookByDate: "2026-03-08",
    airline: "Norse Atlantic",
    includes: ["Personal Item"],
    restrictions: ["Bags extra", "Seat selection extra"],
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    bookingUrl: "https://example.com/book/8",
    source: "The Points Guy",
    postedAt: "2026-03-05T04:00:00Z",
    updatedAt: "2026-03-05T04:00:00Z",
    views: 9876,
    saves: 654,
    tags: ["europe", "flash-sale", "spain", "budget"],
    isHotDeal: true,
    isExpiringSoon: true,
    isHistoricLow: false,
  },
  {
    id: "9",
    type: "package",
    title: "Hawaii Island Hopper - 10 Days",
    description: "Visit 3 islands: Oahu, Maui, and Big Island. All flights and hotels included. Perfect for first Hawaii trip.",
    originalPrice: 4200,
    currentPrice: 2799,
    currency: "USD",
    savingsPercent: 33,
    valueScore: 86,
    originCity: "Los Angeles",
    originCode: "LAX",
    destinationCity: "Honolulu",
    destinationCode: "HNL",
    travelWindow: "Apr - Sep 2026",
    bookByDate: "2026-03-30",
    nights: 10,
    includes: ["All Inter-island Flights", "10 Nights Hotels", "Lei Greeting", "Island Orientation"],
    imageUrl: "https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=800",
    bookingUrl: "https://example.com/book/9",
    source: "Pleasant Holidays",
    postedAt: "2026-03-03T18:00:00Z",
    updatedAt: "2026-03-05T06:00:00Z",
    views: 7234,
    saves: 521,
    tags: ["hawaii", "multi-destination", "beach", "adventure"],
    isHotDeal: false,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "10",
    type: "flight",
    title: "Miami to Rome - $449 RT",
    description: "ITA Airways sale to Italy. Great for foodies and history buffs. Fly direct to the Eternal City.",
    originalPrice: 950,
    currentPrice: 449,
    currency: "USD",
    savingsPercent: 53,
    valueScore: 91,
    originCity: "Miami",
    originCode: "MIA",
    destinationCity: "Rome",
    destinationCode: "FCO",
    travelWindow: "Apr - Jun 2026",
    bookByDate: "2026-03-16",
    airline: "ITA Airways",
    includes: ["Carry-on", "Personal Item", "Meal"],
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    bookingUrl: "https://example.com/book/10",
    source: "SecretFlying",
    postedAt: "2026-03-04T20:00:00Z",
    updatedAt: "2026-03-05T07:00:00Z",
    views: 8123,
    saves: 534,
    tags: ["europe", "italy", "direct-flight", "food"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: true,
  },
  {
    id: "11",
    type: "hotel",
    title: "Amsterdam Canal House - 35% Off",
    description: "Charming boutique hotel overlooking the canals. Perfect location for exploring the city on foot.",
    originalPrice: 320,
    currentPrice: 208,
    currency: "USD",
    savingsPercent: 35,
    valueScore: 78,
    destinationCity: "Amsterdam",
    destinationCode: "AMS",
    travelWindow: "Mar - May 2026",
    bookByDate: "2026-03-22",
    nights: 1,
    hotel: "The Dylan Amsterdam",
    includes: ["Breakfast", "Bike Rental", "Welcome Drink"],
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
    bookingUrl: "https://example.com/book/11",
    source: "Booking.com",
    postedAt: "2026-03-02T14:00:00Z",
    updatedAt: "2026-03-04T10:00:00Z",
    views: 3245,
    saves: 198,
    tags: ["boutique", "europe", "netherlands", "romantic"],
    isHotDeal: false,
    isExpiringSoon: false,
    isHistoricLow: false,
  },
  {
    id: "12",
    type: "flight",
    title: "Seattle to Singapore - $599 RT",
    description: "Singapore Airlines sale. One of the world's best airlines at an incredible price. Stellar service guaranteed.",
    originalPrice: 1400,
    currentPrice: 599,
    currency: "USD",
    savingsPercent: 57,
    valueScore: 95,
    originCity: "Seattle",
    originCode: "SEA",
    destinationCity: "Singapore",
    destinationCode: "SIN",
    travelWindow: "May - Nov 2026",
    bookByDate: "2026-03-19",
    airline: "Singapore Airlines",
    includes: ["Checked Bag", "Meals", "Premium Entertainment", "Amenity Kit"],
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    bookingUrl: "https://example.com/book/12",
    source: "The Flight Deal",
    postedAt: "2026-03-05T01:00:00Z",
    updatedAt: "2026-03-05T01:00:00Z",
    views: 11234,
    saves: 823,
    tags: ["asia", "premium-airline", "singapore", "long-haul"],
    isHotDeal: true,
    isExpiringSoon: false,
    isHistoricLow: true,
  },
];

export const dealStats = {
  totalDeals: 1247,
  avgSavings: 42,
  hotDeals: 23,
  updatedAt: "2026-03-05T09:00:00Z",
};

// Helper function to get deals by city
export function getDealsByCity(citySlug: string): Deal[] {
  const city = popularCities.find(c => c.slug === citySlug || c.code.toLowerCase() === citySlug);
  if (!city) return [];
  
  return sampleDeals.filter(deal => 
    deal.destinationCity.toLowerCase() === city.name.toLowerCase() ||
    deal.destinationCode === city.code
  );
}

// Helper function to get city by slug
export function getCityBySlug(slug: string): City | undefined {
  return popularCities.find(c => c.slug === slug || c.code.toLowerCase() === slug);
}

// Helper function to get deal by ID
export function getDealById(id: string): Deal | undefined {
  return sampleDeals.find(deal => deal.id === id);
}
